### PR TITLE
Graph analytics

### PR DESCRIPTION
**Pull request by nmp76**

### CODE REVIEW

**Comment by ptrgags** [comment]
The Analytics screen looks fine.The Past Workouts still has a problem with text wrapping, I'll make a commit to fix this.

**Comment by ptrgags** [comment]
Okay, I fixed the layout things I mentioned. Since I touched the code, I'll need someone else to look over this to make sure the Past Workouts screen looks good on other phones.

**Comment by jdy27** [comment]
Another issue I found in testing.  If one loads up the Past Workouts screen, goes to current workout screen and saves a workout, then goes back to Past Workouts screen, the new workout will not be displayed in the list until the app is restarted.  I believe this is because there is no OnResume override to allow it to re-populate.

**Comment by rkr35** [comment]
> 
> 
> Another issue I found in testing. If one loads up the Past Workouts screen, goes to current workout screen and saves a workout, then goes back to Past Workouts screen, the new workout will not be displayed in the list until the app is restarted. I believe this is because there is no OnResume override to allow it to re-populate.

**Comment by rkr35** [comment]
Ah, shoot. Accidentally closed the PR!

**Comment by nmp76** [comment]
> Ah, shoot. Accidentally closed the PR!



> > Another issue I found in testing. If one loads up the Past Workouts screen, goes to current workout screen and saves a workout, then goes back to Past Workouts screen, the new workout will not be displayed in the list until the app is restarted. I believe this is because there is no OnResume override to allow it to re-populate.
> 
> Also seeing this.

Pushed out the fix for this. Take a look whenever you get the chance. Added OnResume and OnPause to handle this properly.

**Pull request merged**
