### PR TITLE
initial layout Changes

### PR DESCRIPTION
**Pull request by nmp76**

### CODE REVIEW

**Comment by nmp76** [comment]
Take a look at this and see if it is alright

**Comment by btmosher1** [comment]
I tested the changes and found two bugs.

1. After entering a date range the calculations and graphs display data for the same range, but off by one day. For example, if I enter 4/10/2019 - 4/11/2019 I'm given data from 4/9/2019 - 4/10/2019.

2. The Average Speed graph does not show the values along the x-axis of the graph.

Screenshot_20190516-224134_LapCounter
Screenshot_20190516-224142_LapCounter

**Comment by nmp76** [comment]
> I tested the changes and found two bugs.
> 
> 1. After entering a date range the calculations and graphs display data for the same range, but off by one day. For example, if I enter 4/10/2019 - 4/11/2019 I'm given data from 4/9/2019 - 4/10/2019.
> 2. The Average Speed graph does not show the values along the x-axis of the graph. I'm using my Samsung Galaxy S7.
> 
> Screenshot_20190516-224134_LapCounter
> Screenshot_20190516-224142_LapCounter

Just fixed the Date issue. Going to be seeing i can get the chart to show more Grid lines. I think becuase it was below 1, it doesn't show the other numbers. I added another entry that made the m/s  and yds/s greater than 1 and the grid line showed fine.

**Comment by jdy27** [comment]
> > I tested the changes and found two bugs.
> > 
> > 1. After entering a date range the calculations and graphs display data for the same range, but off by one day. For example, if I enter 4/10/2019 - 4/11/2019 I'm given data from 4/9/2019 - 4/10/2019.
> > 2. The Average Speed graph does not show the values along the x-axis of the graph. I'm using my Samsung Galaxy S7.
> > 
> > Screenshot_20190516-224134_LapCounter
> > Screenshot_20190516-224142_LapCounter
> 
> Just fixed the Date issue. Going to be seeing i can get the chart to show more Grid lines. I think becuase it was below 1, it doesn't show the other numbers. I added another entry that made the m/s and yds/s greater than 1 and the grid line showed fine.

Personally, I don't think trying to get the lines is worth it at this point, especially with how little time we have left, and how small of a detail it is.

**Comment by jdy27** [comment]
tested it on both emulator pixel XL and moto G3.  Issues I was experiencing are gone and everything looks to be working.  Will wait for another person or two to test before merging.

**Comment by rkr35** [comment]
After changing what is graphed through the graph spinner, I have to click on the graph for it to update. Is that normal behavior, or just something weird happening on my side?

**Comment by btmosher1** [comment]
I went through the screen again and it seems the dates and calculations now match what is chosen in the date selector.

**Comment by rkr35** [comment]
> 
> 
> After changing what is graphed through the graph spinner, I have to click on the graph for it to update. Is that normal behavior, or just something weird happening on my side?

Jon saw as much with other devices, so tapping is probably a feature of the library.

**Pull request merged**
